version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "9000:9000"
      - "8123:8123"

  validator:
    build: ./validator
    depends_on:
      - kafka
    command: ["python", "main.py"]

  ingestion:
    build: ./ingestion
    depends_on:
      - kafka
      - clickhouse

  aggregator:
    build: ./aggregator
    command: ["python", "aggregator.py"]
    depends_on:
      - clickhouse

  dashboard:
    build: ./dashboard
    command: ["npm", "run", "start"]
    depends_on:
      - aggregator
    ports:
      - "5173:5173" # example if using Vite